### ISSUE TITLE
Is it working with meteor 1.3 v?

### ISSUE THREAD

**Issue by mesameen** [pfafman/meteor-plivo#1]
Is it working with meteor 1.3 v?

**Comment by pfafman** [comment]
Plivo has an their own [npm](https://github.com/plivo/plivo-node).  You should be using that with meteor 1.3+.
I would assume that works.  If not you will need to fork this and figure it out. I am not currently using this package.

**Comment by pfafman** [comment]
You might also look at the original from which this is forked.

**Comment by mesameen** [comment]
Thankyou @pfafman 
Can you suggest a tool instead of Plivo which is nice to use.
